### ISSUE TITLE
NullPointer in RewardCalculator

### ISSUE THREAD

**Issue by MagMar94** [MagMar94/ParmorelEclipsePlugin#1]
NullPointer in rewardBasedOnSequenceLength on line 244. Is it possible the optimalSequence never gets assigned to anything?

```
okt 09, 2019 10:40:12 AM hvl.projectparmorel.ml.QLearning fixModel
INFO: Number of episodes: 12
okt 09, 2019 10:40:13 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 0 TOTAL REWARD -17100
okt 09, 2019 10:40:13 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 1 TOTAL REWARD -17100
okt 09, 2019 10:40:13 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 2 TOTAL REWARD -18200
okt 09, 2019 10:40:13 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 3 TOTAL REWARD -16000
okt 09, 2019 10:40:13 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 4 TOTAL REWARD -19300
okt 09, 2019 10:40:14 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 5 TOTAL REWARD -18200
okt 09, 2019 10:40:14 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 6 TOTAL REWARD -18200
okt 09, 2019 10:40:14 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 7 TOTAL REWARD -17100
okt 09, 2019 10:40:14 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 8 TOTAL REWARD -17100
okt 09, 2019 10:40:14 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 9 TOTAL REWARD -17100
okt 09, 2019 10:40:15 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 10 TOTAL REWARD -18200
okt 09, 2019 10:40:15 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 11 TOTAL REWARD -16000

!ENTRY org.eclipse.e4.ui.workbench 4 0 2019-10-09 10:40:15.192
!MESSAGE Command 'hvl.plugin.parmorel.commands.repairCommand' failed
!STACK 0
org.eclipse.core.commands.ExecutionException: Error executing 'hvl.plugin.parmorel.commands.repairCommand': java.lang.NullPointerException
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4319)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4143)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3760)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:164)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	... 36 more
Caused by: java.lang.NullPointerException
	at hvl.projectparmorel.reward.RewardCalculator.rewardBasedOnSequenceLength(RewardCalculator.java:244)
	at hvl.projectparmorel.ml.QLearning.bestSequence(QLearning.java:389)
	at hvl.projectparmorel.ml.QLearning.fixModel(QLearning.java:173)
	at hvl.plugin.parmorel.handlers.RepairHandler.fixSelectedModelWith(RepairHandler.java:114)
	at hvl.plugin.parmorel.handlers.RepairHandler.execute(RepairHandler.java:77)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	... 40 more
```

**Comment by MagMar94** [comment]
The error happened when reparing mutants from b after repairing some from a.
