### ISSUE TITLE
Context not in error map

### ISSUE THREAD

**Issue by MagMar94** [MagMar94/ParmorelEclipsePlugin#3]
The context is not in the error map.

This is from repairing the b10 model without any previous knowledge:
```
okt 11, 2019 11:18:10 AM hvl.projectparmorel.knowledge.Knowledge load
INFO: Loading initialized
okt 11, 2019 11:18:10 AM hvl.projectparmorel.knowledge.Knowledge load
INFO: File created: /Applications/Eclipse Modeling.app/Contents/MacOS/knowledge.xml
okt 11, 2019 11:18:10 AM hvl.projectparmorel.knowledge.Knowledge load
INFO: File not found
okt 11, 2019 11:18:14 AM hvl.projectparmorel.ml.QModelFixer fixModel
INFO: Running with preferences [1, 3, 4]
okt 11, 2019 11:18:17 AM hvl.projectparmorel.ml.QModelFixer fixModel
INFO: Errors to fix: [Error 4, message=This Ecore annotation detail with key 'invocationDelegates' contains a bad value
, Error 4, message=This Ecore annotation detail with key 'settingDelegates' contains a bad value
, Error 4, message=This Ecore annotation detail with key 'validationDelegates' contains a bad value
, Error 401, message=The typed element must have a type
, Error 6, message=This Ecore annotation will ignore its nested annotations
]
okt 11, 2019 11:18:17 AM hvl.projectparmorel.ml.QModelFixer fixModel
INFO: Number of episodes: 25

!ENTRY org.eclipse.e4.ui.workbench 4 0 2019-10-11 11:18:19.388
!MESSAGE Command 'hvl.plugin.parmorel.commands.repairCommand' failed
!STACK 0
org.eclipse.core.commands.ExecutionException: Error executing 'hvl.plugin.parmorel.commands.repairCommand': java.lang.NullPointerException
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4319)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4143)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3760)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:164)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	... 36 more
Caused by: java.lang.NullPointerException
	at hvl.projectparmorel.knowledge.ErrorMap.getOptimalActionForErrorCode(ErrorMap.java:71)
	at hvl.projectparmorel.knowledge.HashErrorContextActionDirectory.getOptimalActionForErrorCode(HashErrorContextActionDirectory.java:35)
	at hvl.projectparmorel.knowledge.QTable.getOptimalActionForErrorCode(QTable.java:147)
	at hvl.projectparmorel.knowledge.Knowledge.getOptimalActionForErrorCode(Knowledge.java:53)
	at hvl.projectparmorel.ml.QModelFixer.chooseAction(QModelFixer.java:135)
	at hvl.projectparmorel.ml.QModelFixer.handleStep(QModelFixer.java:266)
	at hvl.projectparmorel.ml.QModelFixer.handleEpisode(QModelFixer.java:218)
	at hvl.projectparmorel.ml.QModelFixer.fixModel(QModelFixer.java:162)
	at hvl.plugin.parmorel.handlers.RepairHandler.fixSelectedModelWith(RepairHandler.java:133)
	at hvl.plugin.parmorel.handlers.RepairHandler.execute(RepairHandler.java:98)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	... 40 more
```

**Comment by MagMar94** [comment]
The model can be fixed by the algorithm. This is the output when fixed as part of the 100 models:
```
okt 11, 2019 11:41:00 AM hvl.projectparmorel.knowledge.Knowledge load
INFO: Loading initialized
okt 11, 2019 11:41:00 AM hvl.projectparmorel.knowledge.Knowledge load
INFO: File found
okt 11, 2019 11:41:00 AM hvl.projectparmorel.knowledge.Knowledge load
INFO: Root found: knowledge
----------------------------------------------------------------------
----------------------------------------------------------------------
STARTING WITH MODEL - 34: b10.ecore
Num. Classes: 14
Num. References: 24
Num. Attributes: 24
Num. Operations: 0
Num. Enums: 0
Num. DataTypes: 4
----------------------------------------------------------------------
----------------------------------------------------------------------
INITIAL ERRORS:
[Error 401, message=The typed element must have a type
]
Size= 1

PREFERENCES: [2, 4]
okt 11, 2019 11:41:00 AM hvl.projectparmorel.ml.QLearning fixModel
INFO: Errors to fix: [Error 401, message=The typed element must have a type
]
okt 11, 2019 11:41:00 AM hvl.projectparmorel.ml.QLearning fixModel
INFO: Number of episodes: 12
okt 11, 2019 11:41:00 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 0 TOTAL REWARD 100
okt 11, 2019 11:41:00 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 1 TOTAL REWARD 200
okt 11, 2019 11:41:01 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 2 TOTAL REWARD 200
okt 11, 2019 11:41:01 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 3 TOTAL REWARD 200
okt 11, 2019 11:41:01 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 4 TOTAL REWARD 200
okt 11, 2019 11:41:01 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 5 TOTAL REWARD 200
okt 11, 2019 11:41:01 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 6 TOTAL REWARD 200
okt 11, 2019 11:41:01 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 7 TOTAL REWARD 200
okt 11, 2019 11:41:01 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 8 TOTAL REWARD 200
okt 11, 2019 11:41:01 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 9 TOTAL REWARD -900
okt 11, 2019 11:41:01 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 10 TOTAL REWARD 200
okt 11, 2019 11:41:01 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 11 TOTAL REWARD 200
okt 11, 2019 11:41:01 AM hvl.projectparmorel.ml.QLearning fixModel
INFO: 
-----------------ALL SEQUENCES FOUND-------------------
SIZE: 12
DISCARDED SEQUENCES: 0
--------::::B E S T   S E Q U E N C E   I S::::---------
Sequence [id=1, seq=[ErrorAction [Error: 401 The typed element must have a type, Action: setEType, Error hierarchy: 0]
, ErrorAction [Error: 401 The typed element must have a type, Action: setEType, Error hierarchy: 0]
], weight=200.0]


TOTAL TIME: 524
COMPLETELY FINISHED!!!!!!
TOTAL EXECUTION TIME: 524
okt 11, 2019 11:41:01 AM hvl.projectparmorel.knowledge.Knowledge save
INFO: Saving initialized
okt 11, 2019 11:41:01 AM hvl.projectparmorel.knowledge.Knowledge save
INFO: document created
okt 11, 2019 11:41:01 AM hvl.projectparmorel.knowledge.Knowledge save
INFO: Saving completed
```

**Comment by MagMar94** [comment]
and another successful run:
```
okt 11, 2019 11:44:38 AM hvl.projectparmorel.knowledge.Knowledge load
INFO: Loading initialized
okt 11, 2019 11:44:38 AM hvl.projectparmorel.knowledge.Knowledge load
INFO: File found
okt 11, 2019 11:44:38 AM hvl.projectparmorel.knowledge.Knowledge load
INFO: Root found: knowledge
----------------------------------------------------------------------
----------------------------------------------------------------------
STARTING WITH MODEL - 34: b10.ecore
Num. Classes: 14
Num. References: 24
Num. Attributes: 24
Num. Operations: 0
Num. Enums: 0
Num. DataTypes: 4
----------------------------------------------------------------------
----------------------------------------------------------------------
INITIAL ERRORS:
[Error 401, message=The typed element must have a type
]
Size= 1

PREFERENCES: [2, 4]
okt 11, 2019 11:44:38 AM hvl.projectparmorel.ml.QLearning fixModel
INFO: Errors to fix: [Error 401, message=The typed element must have a type
]
okt 11, 2019 11:44:38 AM hvl.projectparmorel.ml.QLearning fixModel
INFO: Number of episodes: 12
okt 11, 2019 11:44:38 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 0 TOTAL REWARD 100
okt 11, 2019 11:44:38 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 1 TOTAL REWARD 200
okt 11, 2019 11:44:38 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 2 TOTAL REWARD 200
okt 11, 2019 11:44:38 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 3 TOTAL REWARD 200
okt 11, 2019 11:44:38 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 4 TOTAL REWARD -900
okt 11, 2019 11:44:38 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 5 TOTAL REWARD -900
okt 11, 2019 11:44:38 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 6 TOTAL REWARD 200
okt 11, 2019 11:44:38 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 7 TOTAL REWARD 200
okt 11, 2019 11:44:38 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 8 TOTAL REWARD 200
okt 11, 2019 11:44:38 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 9 TOTAL REWARD 200
okt 11, 2019 11:44:38 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 10 TOTAL REWARD 200
okt 11, 2019 11:44:38 AM hvl.projectparmorel.ml.QLearning handleEpisode
INFO: EPISODE 11 TOTAL REWARD 200
okt 11, 2019 11:44:38 AM hvl.projectparmorel.ml.QLearning fixModel
INFO: 
-----------------ALL SEQUENCES FOUND-------------------
SIZE: 11
DISCARDED SEQUENCES: 1
--------::::B E S T   S E Q U E N C E   I S::::---------
Sequence [id=1, seq=[ErrorAction [Error: 401 The typed element must have a type, Action: setEType, Error hierarchy: 0]
, ErrorAction [Error: 401 The typed element must have a type, Action: setEType, Error hierarchy: 0]
], weight=200.0]


TOTAL TIME: 464
COMPLETELY FINISHED!!!!!!
TOTAL EXECUTION TIME: 465
okt 11, 2019 11:44:38 AM hvl.projectparmorel.knowledge.Knowledge save
INFO: Saving initialized
okt 11, 2019 11:44:38 AM hvl.projectparmorel.knowledge.Knowledge save
INFO: document created
okt 11, 2019 11:44:38 AM hvl.projectparmorel.knowledge.Knowledge save
INFO: Saving completed
```

**Comment by MagMar94** [comment]
Running with the same preferences from the plugin causes error:
```
okt 11, 2019 11:47:37 AM hvl.projectparmorel.ml.QModelFixer fixModel
INFO: Running with preferences [2, 4]
okt 11, 2019 11:47:40 AM hvl.projectparmorel.ml.QModelFixer fixModel
INFO: Errors to fix: [Error 4, message=This Ecore annotation detail with key 'invocationDelegates' contains a bad value
, Error 4, message=This Ecore annotation detail with key 'settingDelegates' contains a bad value
, Error 4, message=This Ecore annotation detail with key 'validationDelegates' contains a bad value
, Error 401, message=The typed element must have a type
, Error 6, message=This Ecore annotation will ignore its nested annotations
]
okt 11, 2019 11:47:40 AM hvl.projectparmorel.ml.QModelFixer fixModel
INFO: Number of episodes: 25

!ENTRY org.eclipse.e4.ui.workbench 4 0 2019-10-11 11:47:42.826
!MESSAGE Command 'hvl.plugin.parmorel.commands.repairCommand' failed
!STACK 0
org.eclipse.core.commands.ExecutionException: Error executing 'hvl.plugin.parmorel.commands.repairCommand': java.lang.NullPointerException
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4319)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4143)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3760)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:164)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	... 36 more
Caused by: java.lang.NullPointerException
	at hvl.projectparmorel.knowledge.ErrorMap.getOptimalActionForErrorCode(ErrorMap.java:71)
	at hvl.projectparmorel.knowledge.HashErrorContextActionDirectory.getOptimalActionForErrorCode(HashErrorContextActionDirectory.java:35)
	at hvl.projectparmorel.knowledge.QTable.getOptimalActionForErrorCode(QTable.java:147)
	at hvl.projectparmorel.knowledge.Knowledge.getOptimalActionForErrorCode(Knowledge.java:53)
	at hvl.projectparmorel.ml.QModelFixer.chooseAction(QModelFixer.java:135)
	at hvl.projectparmorel.ml.QModelFixer.handleStep(QModelFixer.java:266)
	at hvl.projectparmorel.ml.QModelFixer.handleEpisode(QModelFixer.java:218)
	at hvl.projectparmorel.ml.QModelFixer.fixModel(QModelFixer.java:162)
	at hvl.plugin.parmorel.handlers.RepairHandler.fixSelectedModelWith(RepairHandler.java:133)
	at hvl.plugin.parmorel.handlers.RepairHandler.execute(RepairHandler.java:98)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	... 40 more
```

**Comment by MagMar94** [comment]
OK, so I think I have tracked down the problem. The algorithm actually finds more errors when launched from the plugin, as shown in the logs above. I don't understand why yet...
